/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SafeCityUI;

/**
 *
 * @author wmall
 */
public class HomePageUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageUI
     */
    public HomePageUI() {
        super("Safe City");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        LoginPane = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        emailAdminLogin = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        passwordAdminLogin = new javax.swing.JPasswordField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        SignUpPane = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        nameBorrowerCreateAccount = new javax.swing.JTextField();
        cnicBorrowerCreateAccount = new javax.swing.JTextField();
        phoneBorrowerCreateAccount = new javax.swing.JTextField();
        cityBorrowerCreateAccount = new javax.swing.JTextField();
        emailBorrowerCreateAccount = new javax.swing.JTextField();
        addressBorrowerCreateAccount = new javax.swing.JTextField();
        passwordBorrowerCreateAccount = new javax.swing.JTextField();
        borrowerCreateAccountButton = new javax.swing.JButton();
        borrowerMessageLabelCreateAccount = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        PublicPortalPane = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(955, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 91, 133));
        jPanel1.setPreferredSize(new java.awt.Dimension(735, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 37, 63));

        btn_1.setBackground(new java.awt.Color(0, 37, 55));
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.setText("Login");
        btn_1.setPreferredSize(new java.awt.Dimension(73, 33));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(0, 37, 55));
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.setText("SignUp");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(0, 37, 55));
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.setText("Public Portal");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        jPanel3.setBackground(new java.awt.Color(2, 91, 133));
        jPanel3.setPreferredSize(new java.awt.Dimension(735, 650));
        jPanel3.setLayout(new java.awt.CardLayout());

        LoginPane.setBackground(new java.awt.Color(2, 91, 133));

        jLabel33.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("User Login");

        jLabel35.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Email  ");

        emailAdminLogin.setBackground(new java.awt.Color(2, 91, 133));
        emailAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        emailAdminLogin.setToolTipText("");
        emailAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        emailAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdminLoginActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Password  ");

        passwordAdminLogin.setBackground(new java.awt.Color(2, 91, 133));
        passwordAdminLogin.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
        passwordAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        passwordAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordAdminLoginActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("User Type  ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Police", "Rescure" }));

        jButton4.setBackground(new java.awt.Color(0, 37, 55));
        jButton4.setText("Login");

        javax.swing.GroupLayout LoginPaneLayout = new javax.swing.GroupLayout(LoginPane);
        LoginPane.setLayout(LoginPaneLayout);
        LoginPaneLayout.setHorizontalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(emailAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(LoginPaneLayout.createSequentialGroup()
                        .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(26, 26, 26)
                        .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordAdminLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(185, 185, 185))
            .addGroup(LoginPaneLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPaneLayout.setVerticalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPaneLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel33)
                .addGap(136, 136, 136)
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(40, 40, 40)
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(passwordAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel37)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel3.add(LoginPane, "card2");

        SignUpPane.setBackground(new java.awt.Color(2, 91, 133));

        jLabel25.setFont(new java.awt.Font("SketchFlow Print", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Sign UP");

        jLabel26.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name");

        jLabel28.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CNIC");

        jLabel29.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Phone");

        jLabel30.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");

        jLabel38.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("City");

        jLabel39.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Email");

        jLabel40.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Password");

        nameBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        nameBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        nameBorrowerCreateAccount.setToolTipText("");
        nameBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        nameBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBorrowerCreateAccountActionPerformed(evt);
            }
        });

        cnicBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        cnicBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        cnicBorrowerCreateAccount.setToolTipText("");
        cnicBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cnicBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicBorrowerCreateAccountActionPerformed(evt);
            }
        });

        phoneBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        phoneBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        phoneBorrowerCreateAccount.setToolTipText("");
        phoneBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        phoneBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneBorrowerCreateAccountActionPerformed(evt);
            }
        });

        cityBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        cityBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        cityBorrowerCreateAccount.setToolTipText("");
        cityBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cityBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityBorrowerCreateAccountActionPerformed(evt);
            }
        });

        emailBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        emailBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        emailBorrowerCreateAccount.setToolTipText("");
        emailBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        emailBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBorrowerCreateAccountActionPerformed(evt);
            }
        });

        addressBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        addressBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        addressBorrowerCreateAccount.setToolTipText("");
        addressBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        addressBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressBorrowerCreateAccountActionPerformed(evt);
            }
        });

        passwordBorrowerCreateAccount.setBackground(new java.awt.Color(2, 91, 133));
        passwordBorrowerCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        passwordBorrowerCreateAccount.setToolTipText("");
        passwordBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        passwordBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBorrowerCreateAccountActionPerformed(evt);
            }
        });

        borrowerCreateAccountButton.setBackground(new java.awt.Color(2, 91, 133));
        borrowerCreateAccountButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        borrowerCreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        borrowerCreateAccountButton.setText("Create Account");
        borrowerCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerCreateAccountButtonActionPerformed(evt);
            }
        });

        borrowerMessageLabelCreateAccount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        borrowerMessageLabelCreateAccount.setForeground(new java.awt.Color(204, 0, 0));
        borrowerMessageLabelCreateAccount.setText("jLabel1");

        jLabel41.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("User Type  ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Police", "Rescure" }));

        javax.swing.GroupLayout SignUpPaneLayout = new javax.swing.GroupLayout(SignUpPane);
        SignUpPane.setLayout(SignUpPaneLayout);
        SignUpPaneLayout.setHorizontalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnicBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 43, Short.MAX_VALUE)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityBorrowerCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(phoneBorrowerCreateAccount)
                            .addComponent(passwordBorrowerCreateAccount)))
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, 175, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(borrowerMessageLabelCreateAccount))
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel25))
                    .addGroup(SignUpPaneLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(borrowerCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SignUpPaneLayout.setVerticalGroup(
            SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrowerMessageLabelCreateAccount)
                .addGap(29, 29, 29)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(nameBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(cnicBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel38)
                    .addComponent(cityBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(SignUpPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(emailBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordBorrowerCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(borrowerCreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel3.add(SignUpPane, "card2");

        PublicPortalPane.setBackground(new java.awt.Color(2, 91, 133));

        jLabel34.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Public Portal");

        jPanel4.setBackground(new java.awt.Color(2, 91, 133));

        jPanel5.setBackground(new java.awt.Color(2, 91, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Report Query");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jPanel6.setBackground(new java.awt.Color(2, 91, 120));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Rescue Request");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(2, 91, 100));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Check Route");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(2, 91, 120));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Feedback/Suggestion");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PublicPortalPaneLayout = new javax.swing.GroupLayout(PublicPortalPane);
        PublicPortalPane.setLayout(PublicPortalPaneLayout);
        PublicPortalPaneLayout.setHorizontalGroup(
            PublicPortalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublicPortalPaneLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(PublicPortalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        PublicPortalPaneLayout.setVerticalGroup(
            PublicPortalPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublicPortalPaneLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel34)
                .addGap(65, 65, 65)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel3.add(PublicPortalPane, "card2");

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAdminLoginActionPerformed

    private void passwordAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordAdminLoginActionPerformed

    private void nameBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBorrowerCreateAccountActionPerformed

    private void cnicBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicBorrowerCreateAccountActionPerformed

    private void phoneBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneBorrowerCreateAccountActionPerformed

    private void cityBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityBorrowerCreateAccountActionPerformed

    private void emailBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBorrowerCreateAccountActionPerformed

    private void addressBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressBorrowerCreateAccountActionPerformed

    private void passwordBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordBorrowerCreateAccountActionPerformed

    private void borrowerCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerCreateAccountButtonActionPerformed

        
    }//GEN-LAST:event_borrowerCreateAccountButtonActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        
        
         jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(LoginPane);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
       
        
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(SignUpPane);
        jPanel3.repaint();
        jPanel3.revalidate();
        
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
       
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(PublicPortalPane);
        jPanel3.repaint();
        jPanel3.revalidate();
        
    }//GEN-LAST:event_btn_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPane;
    private javax.swing.JPanel PublicPortalPane;
    private javax.swing.JPanel SignUpPane;
    private javax.swing.JTextField addressBorrowerCreateAccount;
    private javax.swing.JButton borrowerCreateAccountButton;
    private javax.swing.JLabel borrowerMessageLabelCreateAccount;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JTextField cityBorrowerCreateAccount;
    private javax.swing.JTextField cnicBorrowerCreateAccount;
    private javax.swing.JTextField emailAdminLogin;
    private javax.swing.JTextField emailBorrowerCreateAccount;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField nameBorrowerCreateAccount;
    private javax.swing.JPasswordField passwordAdminLogin;
    private javax.swing.JTextField passwordBorrowerCreateAccount;
    private javax.swing.JTextField phoneBorrowerCreateAccount;
    // End of variables declaration//GEN-END:variables
}
