/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safecity;


import javax.swing.JOptionPane;
import Classes.Category;
import Classes.Challan;
import Classes.Controller;
import Classes.Notification;
import Classes.NotificationFeed;
import Classes.Person;
import Classes.Employee;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import Classes.Feedback;
import validation.*;
import Classes.Organization;
import Classes.PoliceStation;
import Classes.ProxyNotificationFeed;
import Classes.RescueStation;
import Classes.Vehicle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
/**
 *
 * @author Bilal
 */


public class employeePortal extends javax.swing.JFrame {

    /**
     * Creates new form employeePortal
     */
    
    int cnic=-1;
    
    public employeePortal() {
        super("Employee Portal / Safe City");
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
        jPanel3.removeAll();
        jPanel3.add(jPanel4);
        jPanel3.repaint();
        jPanel3.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        policeReport = new javax.swing.ButtonGroup();
        rescueReport = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Register = new javax.swing.JPanel();
        SignUpPane = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        phoneBorrowerCreateAccount = new javax.swing.JTextField();
        cityBorrowerCreateAccount = new javax.swing.JTextField();
        emailBorrowerCreateAccount = new javax.swing.JTextField();
        addressBorrowerCreateAccount = new javax.swing.JTextField();
        borrowerCreateAccountButton = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        Report = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        Notification = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SendChallan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        personStatus = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        VehicalStatus = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(955, 650));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        jButton1.setBackground(new java.awt.Color(0, 37, 55));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Camera Surviellance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 37, 55));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Notification");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 37, 55));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 37, 55));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Send Challan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 37, 55));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Check Route");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 37, 55));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Registration");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 37, 55));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Log Out");
        jButton10.setMaximumSize(new java.awt.Dimension(93, 23));
        jButton10.setMinimumSize(new java.awt.Dimension(93, 23));
        jButton10.setPreferredSize(new java.awt.Dimension(93, 23));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 37, 55));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Home");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 37, 55));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("View Feedback/Suggestion");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 37, 55));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Suspect Surviellance");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 37, 55));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Vehicle Surviellance");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Azonix", 2, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SafeCity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel22)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(737, 650));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 204, 102));

        jTable2.setBackground(new java.awt.Color(255, 204, 102));
        jTable2.setForeground(new java.awt.Color(54, 33, 89));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 568, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, "card8");

        jPanel4.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, "card7");

        Register.setBackground(new java.awt.Color(255, 204, 102));
        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpPane.setBackground(new java.awt.Color(255, 204, 102));
        SignUpPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("SketchFlow Print", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 33, 89));
        jLabel26.setText("Register User");
        SignUpPane.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 31, -1, 31));

        jLabel32.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(54, 33, 89));
        jLabel32.setText("Phone");
        SignUpPane.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 205, 54, -1));

        jLabel34.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(54, 33, 89));
        jLabel34.setText("Address");
        SignUpPane.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 298, 70, -1));

        jLabel38.setBackground(new java.awt.Color(255, 255, 204));
        jLabel38.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(54, 33, 89));
        jLabel38.setText("City");
        SignUpPane.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 298, -1, -1));

        jLabel39.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(54, 33, 89));
        jLabel39.setText("Email");
        SignUpPane.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 399, 49, -1));

        jLabel40.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(54, 33, 89));
        jLabel40.setText("Password");
        SignUpPane.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 399, 87, -1));

        phoneBorrowerCreateAccount.setBackground(new java.awt.Color(255, 255, 204));
        phoneBorrowerCreateAccount.setToolTipText("");
        phoneBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        phoneBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneBorrowerCreateAccountActionPerformed(evt);
            }
        });
        SignUpPane.add(phoneBorrowerCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 200, 200, 26));

        cityBorrowerCreateAccount.setBackground(new java.awt.Color(255, 255, 204));
        cityBorrowerCreateAccount.setToolTipText("");
        cityBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cityBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityBorrowerCreateAccountActionPerformed(evt);
            }
        });
        SignUpPane.add(cityBorrowerCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 293, 200, 26));

        emailBorrowerCreateAccount.setBackground(new java.awt.Color(255, 255, 204));
        emailBorrowerCreateAccount.setToolTipText("");
        emailBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        emailBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBorrowerCreateAccountActionPerformed(evt);
            }
        });
        SignUpPane.add(emailBorrowerCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 394, 245, 26));

        addressBorrowerCreateAccount.setBackground(new java.awt.Color(255, 255, 204));
        addressBorrowerCreateAccount.setForeground(new java.awt.Color(54, 33, 89));
        addressBorrowerCreateAccount.setToolTipText("");
        addressBorrowerCreateAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        addressBorrowerCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressBorrowerCreateAccountActionPerformed(evt);
            }
        });
        SignUpPane.add(addressBorrowerCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 293, 245, 26));

        borrowerCreateAccountButton.setBackground(new java.awt.Color(255, 255, 102));
        borrowerCreateAccountButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        borrowerCreateAccountButton.setForeground(new java.awt.Color(54, 33, 89));
        borrowerCreateAccountButton.setText("Create Account");
        borrowerCreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerCreateAccountButtonActionPerformed(evt);
            }
        });
        SignUpPane.add(borrowerCreateAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 530, 289, 39));

        jLabel41.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(54, 33, 89));
        jLabel41.setText("User Type  ");
        SignUpPane.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox2.setForeground(new java.awt.Color(54, 33, 89));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Police", "Rescue" }));
        SignUpPane.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 175, 29));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 204));
        jPasswordField1.setForeground(new java.awt.Color(54, 33, 89));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(2, 16));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(2, 16));
        SignUpPane.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 200, 30));

        Register.add(SignUpPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 4, 740, 660));

        jPanel3.add(Register, "card6");

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(737, 650));

        jPanel5.setBackground(new java.awt.Color(255, 204, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("Choose Query Type:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 51, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(2, 91, 133));
        policeReport.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton1.setText("Kidnapping");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(2, 91, 133));
        policeReport.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton2.setText("Murder");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(2, 91, 133));
        policeReport.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton4.setText("Suicide");
        jPanel5.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, -1));

        jRadioButton5.setBackground(new java.awt.Color(2, 91, 133));
        policeReport.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton5.setText("Theft");
        jPanel5.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(2, 91, 133));
        policeReport.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton6.setText("Other");
        jPanel5.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(54, 33, 89));
        jLabel20.setText("Description:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jTextArea3.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(54, 33, 89));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 358, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(54, 33, 89));
        jLabel21.setText("Location:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 204));
        jTextField12.setForeground(new java.awt.Color(54, 33, 89));
        jPanel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 358, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(54, 33, 89));
        jButton8.setText("Report");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(54, 33, 89));
        jLabel25.setText("Information of Query:");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jTabbedPane1.addTab("Report to Police Station", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 204, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(623, 595));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(54, 33, 89));
        jLabel27.setText("Choose Station: ");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jRadioButton7.setBackground(new java.awt.Color(2, 91, 133));
        rescueReport.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton7.setText("Ambulance");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jRadioButton8.setBackground(new java.awt.Color(2, 91, 133));
        rescueReport.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton8.setText("Fire Burgade");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jRadioButton9.setBackground(new java.awt.Color(2, 91, 133));
        rescueReport.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(54, 33, 89));
        jRadioButton9.setText("Other");
        jPanel6.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(54, 33, 89));
        jLabel28.setText("Description:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jTextArea4.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(54, 33, 89));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 358, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(54, 33, 89));
        jLabel29.setText("Location:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jTextField15.setBackground(new java.awt.Color(255, 255, 204));
        jTextField15.setForeground(new java.awt.Color(54, 33, 89));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 358, -1));

        jButton9.setBackground(new java.awt.Color(255, 255, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(54, 33, 89));
        jButton9.setText("Report");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(54, 33, 89));
        jLabel33.setText("Information of Emergency:");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jTabbedPane1.addTab("Report to Rescue Station", jPanel6);

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(Report, "card4");

        Notification.setBackground(new java.awt.Color(255, 204, 102));
        Notification.setPreferredSize(new java.awt.Dimension(737, 650));

        jScrollPane1.setBackground(new java.awt.Color(2, 91, 133));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(729, 650));

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Notification Type", "Description", "Location", "Reporter Phone/Department", "Stutus"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(2, 91, 133));
        jTable1.setPreferredSize(new java.awt.Dimension(729, 650));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout NotificationLayout = new javax.swing.GroupLayout(Notification);
        Notification.setLayout(NotificationLayout);
        NotificationLayout.setHorizontalGroup(
            NotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        NotificationLayout.setVerticalGroup(
            NotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(Notification, "card3");

        SendChallan.setBackground(new java.awt.Color(255, 204, 102));
        SendChallan.setForeground(new java.awt.Color(255, 255, 255));
        SendChallan.setMinimumSize(new java.awt.Dimension(0, 0));
        SendChallan.setPreferredSize(new java.awt.Dimension(737, 650));
        SendChallan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 33, 89));
        jLabel2.setText("Vehicle Infomation:");
        SendChallan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 25));

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setForeground(new java.awt.Color(54, 33, 89));
        SendChallan.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 230, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 33, 89));
        jLabel8.setText("Challan Details:");
        SendChallan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 281, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(54, 33, 89));
        jLabel11.setText("Challan Reason:");
        SendChallan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(54, 33, 89));
        jLabel12.setText("Generate Challan");
        SendChallan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(54, 33, 89));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        SendChallan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 400, 420, 120));

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(54, 33, 89));
        jButton6.setText("Send Challan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        SendChallan.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(54, 33, 89));
        jLabel13.setText("Registration Number:");
        SendChallan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("Challan Amount:");
        SendChallan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jTextField11.setBackground(new java.awt.Color(255, 255, 204));
        jTextField11.setForeground(new java.awt.Color(54, 33, 89));
        SendChallan.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 125, 30));

        jPanel3.add(SendChallan, "card2");

        personStatus.setBackground(new java.awt.Color(255, 204, 102));

        jScrollPane6.setBackground(new java.awt.Color(255, 204, 102));

        jTable3.setBackground(new java.awt.Color(255, 204, 102));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "CNIC", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jButton15.setBackground(new java.awt.Color(255, 204, 102));
        jButton15.setText("SAVE");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 204, 102));
        jButton16.setText("Search");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personStatusLayout = new javax.swing.GroupLayout(personStatus);
        personStatus.setLayout(personStatusLayout);
        personStatusLayout.setHorizontalGroup(
            personStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(personStatusLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(personStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        personStatusLayout.setVerticalGroup(
            personStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personStatusLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(personStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(personStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.add(personStatus, "card8");

        VehicalStatus.setBackground(new java.awt.Color(255, 204, 102));

        jScrollPane7.setBackground(new java.awt.Color(255, 204, 102));

        jTable4.setBackground(new java.awt.Color(255, 204, 102));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "CNIC", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jButton17.setBackground(new java.awt.Color(255, 204, 102));
        jButton17.setText("SAVE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 204, 102));
        jButton18.setText("Search");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VehicalStatusLayout = new javax.swing.GroupLayout(VehicalStatus);
        VehicalStatus.setLayout(VehicalStatusLayout);
        VehicalStatusLayout.setHorizontalGroup(
            VehicalStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(VehicalStatusLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(VehicalStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(235, 235, 235)
                .addGroup(VehicalStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        VehicalStatusLayout.setVerticalGroup(
            VehicalStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicalStatusLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGroup(VehicalStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehicalStatusLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel18))
                    .addGroup(VehicalStatusLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(VehicalStatus, "card8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new safecity.RuntimeSurviellance().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(Notification);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //////////////
       // jTable1.setRowHeight(jTable1.getRowHeight() + 3);
        NotificationFeed instance = ProxyNotificationFeed.getInstance();
        instance.setNotifications();
        List<Notification> notificationList = instance.getNotifications();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        
        for(int i=0;i<notificationList.size();i++)
        {
            Notification currentNotification=notificationList.get(i);
            
            String Status;
            String phone=currentNotification.getPhone();
            if(phone==null)
                phone="Safecity Depatment";
            
            if(currentNotification.getStatus()==0)
                 Status="Not Resolved Yet";
            else if (currentNotification.getStatus()== 1)
                 Status="Ongoing..";
            else 
                 Status="Resolved";
            
            model.addRow(new Object[]{currentNotification.getCategory(),currentNotification.getDescription()
            , currentNotification.getLocation(),phone,Status});
            
            
        }
        //jTable1.setRowHeight(5,60);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(Report);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(SendChallan);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new safecity.GoogleMapsSample().setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(Register);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void phoneBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneBorrowerCreateAccountActionPerformed

    private void cityBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityBorrowerCreateAccountActionPerformed

    private void emailBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBorrowerCreateAccountActionPerformed

    private void addressBorrowerCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressBorrowerCreateAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressBorrowerCreateAccountActionPerformed

    private void borrowerCreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowerCreateAccountButtonActionPerformed

        
        String usertype=(String)jComboBox2.getSelectedItem();
        
        String address= addressBorrowerCreateAccount.getText();
        
        String city= cityBorrowerCreateAccount.getText();
        
        String email= emailBorrowerCreateAccount.getText();
        
        String phone= phoneBorrowerCreateAccount.getText();
        
        String password= jPasswordField1.getText();
        
        boolean success=true;
        StringBuilder errorMessage=new StringBuilder("Kindly enter ");
       
       // displaying error(s) or information
       
       
      
      if(usertype.equals("Employee"))
               errorMessage=errorMessage.append("Employee's ");
       else
               errorMessage=errorMessage.append("Organization's ");
       
       
      if(phone.isEmpty()){
        // if(!success)
          //     errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("Phone Number");
         success=false;
       }
           
       if(address.isEmpty()){
         if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("Address");
         success=false;
       }
       if(city.isEmpty()){
           if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("City");
         success=false;
       }
       
       if(email.isEmpty()){
           if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("Email");       
         success=false;
       }
       
       if(password.isEmpty()){
           if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("Passoword");       
         success=false;
       }
        
       if(!password.isEmpty())
      {
      boolean passwordValid=password.length()>=6;
      
      if(!passwordValid)
      {
          if(success)
          {
              //errorMessage=errorMessage.delete(0, errorMessage.length()-1);
              errorMessage=new StringBuilder("Password should be atleast six characters");        
          }
          
          else 
          {
               
               errorMessage=errorMessage.append("\nPassword should be atleast six characters");
          }
          
          success=false;
      }
      }
      
       
      if(!phone.isEmpty())
      {
      boolean phoneValid=PhoneValidation.validate(phone);
      
      if(!phoneValid)
      {
          if(success)
          {
              //errorMessage=errorMessage.delete(0, errorMessage.length()-1);
              errorMessage=new StringBuilder("Enter a Valid Phone Number");        
          }
          
          else 
          {
               
               errorMessage=errorMessage.append("\nEnter a Valid Phone Number");
          }
          
          success=false;
      }
      }
      
      if(!email.isEmpty())
      {
      boolean emailValid=EmailValidation .validate(email);
      
      if(!emailValid)
      {
          if(success)
          {
              //errorMessage=errorMessage.delete(0, errorMessage.length()-1);
              errorMessage=new StringBuilder("Enter a Valid Email");        
          }
          
          else 
          {
               
               errorMessage=errorMessage.append("\nEnter a Valid Email");
          }
          
          success=false;
      }
      }
      
      
      
     
      
      int index=errorMessage.lastIndexOf(",");
       if(index!=-1)
           errorMessage.insert(index, " and");
       
      errorMessage.append(".");
        
     if(success )
       {
       
           if(usertype.equals("Employee"))
           {
           Employee personObj=new Employee();
           
           
           personObj.setEmail(email);
           personObj.setPhonenumber(phone);
           personObj.setUsertype("emp");
           personObj.setPassword(password);
           personObj.setAddress(address);
           personObj.setCity(city);
           //personObj.setId(2);
           //personObj.setCnic("");
           boolean empAdded=Employee.getInstance().addEmployee(personObj);
           if(empAdded){
                JOptionPane.showMessageDialog(this,"Employee Resgistered Successfully");
//                 SendMail.send(email, "Safcity Registration", 
//                        "You have been Registered on Safecity", "shahrozahmad90@gmail.com", "SHAHROZ234crap");
           }
           else 
                JOptionPane.showMessageDialog(this,"Employee already Resgistered");
           }
           else
           {
               Organization orgObj;
               
               if(usertype.equals("Police")){
                    orgObj=new PoliceStation();
                    orgObj.setOrganizationtype("police");
               }
               else{
                   orgObj=new RescueStation();
                   orgObj.setOrganizationtype("rescue");
               }
               orgObj.setEmail(email);
               orgObj.setLocation(address);
               orgObj.setPhonenumber(phone);
               orgObj.setPassword(password);
               orgObj.setCity(city);
               
               boolean orgAdded=Employee.getInstance().addOrganization(orgObj);
               if(orgAdded){
//                   
//                   SendMail.send(email, "Safcity Registration", 
//                        "You have been Registered on Safecity", "shahrozahmad90@gmail.com", "SHAHROZ234crap");
                JOptionPane.showMessageDialog(this,"Organization Resgistered Successfully");
                
               }
               else 
                JOptionPane.showMessageDialog(this,"Organization already Resgistered");
           }
       }
       
       else
           JOptionPane.showConfirmDialog(null,errorMessage,"Insufficient Information",JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        
     
        
    }//GEN-LAST:event_borrowerCreateAccountButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    
        Category category=null;
        if(jRadioButton1.isSelected())
            category=Category.Kidnapping;
         
        else if(jRadioButton2.isSelected())
            category=Category.Murder;
        else if(jRadioButton5.isSelected())
            category=Category.Theft;
        else if(jRadioButton4.isSelected())
            category=Category.Suicide;
        else if(jRadioButton6.isSelected())
            category=Category.Other;
        
        String reportDescription =jTextArea3.getText();
        String reportLocation =jTextField12.getText();
        
        
        boolean success=true;
        StringBuilder errorMessage=new StringBuilder("Kindly enter ");
       
       // displaying error(s) or information
       
       if(reportDescription.isEmpty()){
           
         errorMessage=errorMessage.append("Description about the Incident");
         success=false;
       }
       
       if(reportLocation.isEmpty()){
           if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("incident Location");       
         success=false;
       }
       
       
       if(category==(null)){
           if(!success)
               errorMessage=errorMessage.append(", ");
           else
               errorMessage=new StringBuilder("Kindly; ");
         errorMessage=errorMessage.append("Choose an Incident catogory \n");
         success=false;
       }
       
       int index=errorMessage.lastIndexOf(",");
       if(index!=-1)
           errorMessage.insert(index, " and");
       
      errorMessage.append(".");
      
       if(success)
       {
       
           Notification notificationObj=new Notification();
           notificationObj.setCategory(category);
           
           notificationObj.setDescription(reportDescription);
           notificationObj.setLocation(reportLocation);
           notificationObj.setStatus(0);
          
           NotificationFeed instance = ProxyNotificationFeed.getInstance();
           instance.setNotifications();
           
           boolean reportStatus=instance.addNotification(notificationObj);
           if(reportStatus)
                JOptionPane.showMessageDialog(this,"Incident Reported Successfully");
           else if(reportStatus)
                JOptionPane.showMessageDialog(this,"Could not report the incident");
       }
       
       else
           JOptionPane.showConfirmDialog(null,errorMessage,"Insufficient Information",JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    
        Category category=null;
        if(jRadioButton7.isSelected())
            category=Category.Ambulance;
        else if(jRadioButton8.isSelected())
            category=Category.FireBrigade; 
        
        else if(jRadioButton9.isSelected())
            category=Category.Other;
        
        String reportDescription =jTextArea4.getText();
        String reportLocation =jTextField15.getText();
        
        
        boolean success=true;
        StringBuilder errorMessage=new StringBuilder("Kindly enter ");
       
       // displaying error(s) or information
       
       if(reportDescription.isEmpty()){
           
         errorMessage=errorMessage.append("Description about the Emergency");
         success=false;
       }
       
       if(reportLocation.isEmpty()){
           if(!success)
               errorMessage=errorMessage.append(", ");
         errorMessage=errorMessage.append("Emergency Location");       
         success=false;
       }
       
       
       if(category==(null)){
           if(!success)
               errorMessage=errorMessage.append(", ");
           else
               errorMessage=new StringBuilder("Kindly; ");
         errorMessage=errorMessage.append("Choose a Rescue Station \n");
         success=false;
       }
       
       int index=errorMessage.lastIndexOf(",");
       if(index!=-1)
           errorMessage.insert(index, " and");
       
      errorMessage.append(".");
      
       if(success)
       {
       
           Notification notificationObj=new Notification();
           notificationObj.setCategory(category);
    
           notificationObj.setDescription(reportDescription);
           notificationObj.setLocation(reportLocation);
           notificationObj.setStatus(0);
           
           NotificationFeed instance = ProxyNotificationFeed.getInstance();
           instance.setNotifications();
           
           boolean reportStatus=instance.addNotification(notificationObj);
           if(reportStatus)
                JOptionPane.showMessageDialog(this,"Resquest submitted Successfully");
           else if(reportStatus)
                JOptionPane.showMessageDialog(this,"Could not make the request");
       }
       
       else
           JOptionPane.showConfirmDialog(null,errorMessage,"Insufficient Information",JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        ////
        javax.swing.JTable source=(javax.swing.JTable)evt.getSource();
        int rowAtClick =source.rowAtPoint(evt.getPoint());
        ///
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
       
        if(rowAtClick!=-1){
            
        Category catogory=(Category)model.getValueAt(rowAtClick, 0);
        String description=(String)model.getValueAt(rowAtClick, 1);
        String location =(String)model.getValueAt(rowAtClick, 2);
        String repoter=(String)model.getValueAt(rowAtClick, 3);
        String status=(String)model.getValueAt(rowAtClick, 4);
        
        JtableInfoEmployee infoForm=new JtableInfoEmployee(catogory,description,repoter,status,location);
        infoForm.setVisible(true);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       HomePageUI ui= new HomePageUI();
        
        ui.getCardPanel().removeAll();
        ui.getCardPanel().repaint();
        ui.getCardPanel().revalidate();

        ui.getCardPanel().add(ui.getloginPanel());
        ui.getCardPanel().repaint();
        ui.getCardPanel().revalidate();
        
        ui.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(jPanel4);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
          jPanel3.removeAll();
        jPanel3.add(jPanel7);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //////////////////
        
        NotificationFeed instance = ProxyNotificationFeed.getInstance();
        instance.setNotifications();
        List<Feedback> feedbackList=instance.getFeedback();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        for(int i=0;i<feedbackList.size();i++)
        {
            Feedback currentFeedback=feedbackList.get(i);
            
              String type;
            if(currentFeedback.getCatogory())
                 type="Suggestion";
           
            else 
                 type="Feedback";
            
            model.addRow(new Object[]{type,currentFeedback.getMessage()});
            
            
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        ///////////
         javax.swing.JTable source=(javax.swing.JTable)evt.getSource();
        int rowAtClick =source.rowAtPoint(evt.getPoint());
        ///
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
       
        if(rowAtClick!=-1){
            
        String catogory=(String)model.getValueAt(rowAtClick, 0);
        
        String description=(String)model.getValueAt(rowAtClick, 1);
        
        
        Mesage infoForm=new Mesage(catogory,description);
        infoForm.setVisible(true);
        }
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//         EntityManager em = Controller.getManager();
//        Person p = new Person();
//        p.setAddress("hello");
//        p.setCity("900");
//        p.setCnic("new");
//        p.setEmail("ksshebb@gmail.com");
//        p.setName("asd");
//        p.setUsertype("asdas");
//        p.setPhonenumber("also");
//        
//        em.getTransaction().begin();
//        em.persist(p);
//        em.getTransaction().commit();
//
//Vehicle v = new Vehicle();
//v.setCnic("new");
//v.setRegistrationnumber("200");
//v.setVehicletype("nope");
//        em.getTransaction().begin();
//        em.persist(v);
//        em.getTransaction().commit();
        
             
        // TODO add your handling code here:
        String registration = jTextField1.getText();
        Integer amount = Integer.parseInt(jTextField11.getText());
        String reason = jTextArea1.getText();
        Person p = Controller.vehicleRegistrationLookup(registration);
        Date currentDate = new Date();
        // convert date to calendar
        Calendar c = Calendar.getInstance();
        c.setTime(currentDate);
         c.add(Calendar.DATE, 1);
         // convert calendar to date
         
          
        Date currentDatePlusOne = c.getTime();
         java.sql.Date issueDate = new java.sql.Date(currentDate.getTime());
         java.sql.Date expiryDate =  new java.sql.Date(currentDatePlusOne.getTime());
         
         Challan challan = new Challan();
         challan.setAmount(amount);
         challan.setDuedate(currentDate);
         challan.setIssuedate(issueDate);
         challan.setReason(reason);
         challan.setRegistrationnumber(registration);
        
        if(p != null){
            Controller.sendChallan(challan, p);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(personStatus);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
        Connection myconobj;
    Statement mystatobj;
    ResultSet myresobj;
    String query=null;
    
   
        try {
            myconobj = DriverManager.getConnection("jdbc:derby://localhost:1527/SafeCityDB");
         mystatobj = myconobj.createStatement();
     
        
        
        
DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
                model1.setRowCount(0);
           myresobj =  mystatobj.executeQuery("Select * from trackingfaceid where status= "+false);
                    while(myresobj.next())  {
                int id=myresobj.getInt(1);
                int reg=myresobj.getInt(2);
                boolean status=myresobj.getBoolean(3);
             
               model1.addRow(new Object[]{id, reg,status});
                
                
            }
                    
                    } catch (SQLException ex) {
            Logger.getLogger(employeePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.add(VehicalStatus);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        cnic=-1;
        ArrayList  <trackinglist> list=new ArrayList();

   
   
       
         Connection myconobj;
    Statement mystatobj;
    ResultSet myresobj;
    String query=null;
    
   
        try {
            myconobj = DriverManager.getConnection("jdbc:derby://localhost:1527/SafeCityDB");
         mystatobj = myconobj.createStatement();
     
        
        
        
       
DefaultTableModel model1 = (DefaultTableModel) jTable4.getModel();
                model1.setRowCount(0);
           myresobj =  mystatobj.executeQuery("Select * from trackingreg where status= "+false);
           
                    while(myresobj.next())  {
                        trackinglist l=new trackinglist();
                        
                 l.setId(myresobj.getInt(1));
                 l.setkey(myresobj.getInt(2));
                l.setStatus(myresobj.getBoolean(3));
             
               model1.addRow(new Object[]{l.getId(), l.getkey(),l.getStatus()});
               list.add(l);
                
                
            }        // TODO add your handling code here:
        
        } catch (SQLException ex) {
            Logger.getLogger(employeePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        try{
            int row=jTable3.getSelectedRow();
            int s= (int) (jTable3.getModel().getValueAt(row, 1));
            String ss=String.valueOf(s);
            jLabel4.setText(ss);

            jLabel15.setText("");

        }
        catch(Exception e)
        {
            cnic=-1;
            jLabel15.setText("TABLE IS EMPTY");
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        if(cnic==-1)
        {

        }

        else
        {

            long millis=System.currentTimeMillis();
            java.sql.Date date=new java.sql.Date(millis);
            java.sql.Time time=new java.sql.Time(millis);
            Statement mystatobj;
            ResultSet myresobj;
            Connection myconobj = null;

            try {
                myconobj = DriverManager.getConnection("jdbc:derby://localhost:1527/SafeCityDB");

                String query = "update trackingfaceid set STATUS = ? where CNIC = ?";
                PreparedStatement preparedStmt2 = myconobj.prepareStatement(query);
                preparedStmt2.setBoolean   (1, true);
                preparedStmt2.setInt(2,  cnic);
                preparedStmt2.execute();

                int k=     (int) ((Math.random() * ( 10 - 0 )) + 0);
                String l=null;

                if(k==0)
                {
                    l="JOHAR TOWN A BLOCK STREET NO 23";
                }
                if(k==1)
                {
                    l="JOHAR TOWN C BLOCK STREET NO 2";
                }

                if(k==2)
                {
                    l="WAPDA TOWN D BLOCK STREET NO 11";
                }

                if(k==3)
                {
                    l="DEFENCE HOUSING SCHEME JJ BLOCK STREET NO 7";
                }

                if(k==4)
                {
                    l="IQBAL TOWN KASHMIR  BLOCK STREET NO 9";
                }

                if(k==5)
                {
                    l="BAHRIA TOWN JASMINE BLOCK STREET NO 5";
                }

                if(k==6)
                {
                    l="PCSIR L BLOCK STREET NO 17";
                }

                if(k==7)
                {
                    l="SHADMAN C BLOCK STREET NO 12";
                }

                if(k==8)
                {
                    l="SHALIMAR GARDEN F BLOCK STREET NO 1";
                }

                if(k==9)
                {
                    l="CANAL VIEW FF BLOCK STREET NO 2";
                }

                // the mysql insert statement

                query = " insert into facefound (CNIC,EXACTDATE,EXACTTIME,PLACE)"
                + " values (?, ?,?,?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = myconobj.prepareStatement(query);
                preparedStmt.setInt (1, cnic);
                preparedStmt.setDate(2, date);
                preparedStmt.setTime(3, time);
                preparedStmt.setString(4, l);
                preparedStmt.execute();

                jLabel15.setText("Saved");
                cnic=-1;
            } catch (SQLException e) {

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(jLabel16.getText()=="")
        {
            jLabel18.setText("No value selected");
        }
        else
        {cnic=Integer.parseInt(jLabel16.getText());

            jLabel16.setText("");
            jLabel18.setText("Found");// TODO add your handling code here:
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        try{
            int row=jTable4.getSelectedRow();
            int s= (int) (jTable4.getModel().getValueAt(row, 1));
            String ss=String.valueOf(s);
            jLabel16.setText(ss);

            jLabel18.setText("");

        }
        catch(Exception e)
        {
            cnic=-1;
            jLabel18.setText("TABLE IS EMPTY");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        if(cnic==-1)
        {

        }
        else
        {
            long millis=System.currentTimeMillis();
            java.sql.Date date=new java.sql.Date(millis);
            java.sql.Time time=new java.sql.Time(millis);
            Statement mystatobj;
            ResultSet myresobj;
            Connection myconobj;

            try {
                myconobj = DriverManager.getConnection("jdbc:derby://localhost:1527/SafeCityDB");

                String query = "update trackingreg set STATUS = ? where REGISTRATION_NUM = ?";
                PreparedStatement preparedStmt2 = myconobj.prepareStatement(query);
                preparedStmt2.setBoolean   (1, true);
                preparedStmt2.setInt(2, cnic);
                preparedStmt2.execute();

                int k=     (int) ((Math.random() * ( 10 - 0 )) + 0);
                String l=null;

                if(k==0)
                {
                    l="JOHAR TOWN A BLOCK STREET NO 23";
                }
                if(k==1)
                {
                    l="JOHAR TOWN C BLOCK STREET NO 2";
                }

                if(k==2)
                {
                    l="WAPDA TOWN D BLOCK STREET NO 11";
                }

                if(k==3)
                {
                    l="DEFENCE HOUSING SCHEME JJ BLOCK STREET NO 7";
                }

                if(k==4)
                {
                    l="IQBAL TOWN KASHMIR  BLOCK STREET NO 9";
                }

                if(k==5)
                {
                    l="BAHRIA TOWN JASMINE BLOCK STREET NO 5";
                }

                if(k==6)
                {
                    l="PCSIR L BLOCK STREET NO 17";
                }

                if(k==7)
                {
                    l="SHADMAN C BLOCK STREET NO 12";
                }

                if(k==8)
                {
                    l="SHALIMAR GARDEN F BLOCK STREET NO 1";
                }

                if(k==9)
                {
                    l="CANAL VIEW FF BLOCK STREET NO 2";
                }

                // the mysql insert statement

                query = " insert into VEHICLEFOUND (REGISTRATION_NUM,EXACTDATE,EXACTTIME,PLACE)"
                + " values (?, ?,?,?)";

                // create the mysql insert preparedstatement
                PreparedStatement preparedStmt = myconobj.prepareStatement(query);
                preparedStmt.setInt (1,cnic);
                preparedStmt.setDate(2, date);
                preparedStmt.setTime(3, time);
                preparedStmt.setString(4, l);
                preparedStmt.execute();

                jLabel18.setText("saved");
                cnic=-1;
            } catch (SQLException ex) {

            }
        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handli;
        if(jLabel16.getText()=="")
        {
            jLabel8.setText("No value selected");
        }
        else
        {cnic=Integer.parseInt(jLabel16.getText());

            jLabel16.setText("");
            jLabel18.setText("Found");// TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeePortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Notification;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel Report;
    private javax.swing.JPanel SendChallan;
    private javax.swing.JPanel SignUpPane;
    private javax.swing.JPanel VehicalStatus;
    private javax.swing.JTextField addressBorrowerCreateAccount;
    private javax.swing.JButton borrowerCreateAccountButton;
    private javax.swing.JTextField cityBorrowerCreateAccount;
    private javax.swing.JTextField emailBorrowerCreateAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JPanel personStatus;
    private javax.swing.JTextField phoneBorrowerCreateAccount;
    private javax.swing.ButtonGroup policeReport;
    private javax.swing.ButtonGroup rescueReport;
    // End of variables declaration//GEN-END:variables
}
